// eslint-disable-next-line import/prefer-default-export
export const TRIP_TYPES = {
  SET_ORIGIN: 'SET_ORIGIN',
  SET_DESTINATION: 'SET_DESTINATION',
  SET_WAYPOINTS: 'SET_WAYPOINTS',
  SET_LINE: 'SET_LINE',
  SET_POIS: 'SET_POIS',
  SET_TRIP: 'SET_TRIP',
  REMOVE_WAYPOINT: 'REMOVE_WAYPOINT',
  SET_MINUTES: 'SET_MINUTES',
};
